name: Test CI with Python, Behave, and PlayWright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: Install Dependencies with UV
        run: uv sync
        working-directory: ${{github.workspace}}

      - name: Install Web Browsers
        run: playwright install --with-deps

      - name: Run Behave Tests
        run: behave